version: "3"
volumes:
  db-store:
  php-fpm-socket:
services:
  app:
    build: ./map-event/php
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ./:/work/laravel
    #restart: always

  web:
    build: ./map-event/nginx
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ./:/work/laravel
    #restart: always

  db:
    build: ./map-event/mysql
    volumes:
      - db-store:/var/lib/mysql
    #restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=db
      - PMA_USER=admin
      - PMA_PASSWORD=pass
    volumes:
      - ./map-event/phpmyadmin/sessions:/sessions
    #restart: always
